"""new field for model 

Revision ID: 524326803254
Revises: 07a9d8fa9149
Create Date: 2024-11-12 19:23:54.037820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524326803254'
down_revision: Union[str, None] = '07a9d8fa9149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_word', sa.Column('formatted_draft', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents_word', 'formatted_draft')
    # ### end Alembic commands ###
